from app.api.nsmodels.auth import (
    auth_ns,
    registration_parser,
    auth_parser,
    request_reset_password_parser,
    reset_password_parser,
)
from app.api.nsmodels.accounts import (
    accounts_ns,
    account_model,
    current_user_model,
    account_update_parser,
    account_update_response_model,
    account_list_response_model,
    account_delete_response_model,
    grant_permissions_parser,
    permission_model,
    user_permission_model,
    permission_list_response_model,
    user_permission_list_response_model,
    permission_action_response_model,
    error_model,
)
from app.api.nsmodels.permissions import (
    permissions_ns,
    permission_create_parser,
    permission_model as catalog_permission_model,
    permission_list_response_model as catalog_permission_list_response_model,
    permission_create_response_model,
    permission_delete_response_model,
    error_model as permissions_error_model,
    JWT_OR_API_KEY as PERMISSIONS_JWT_OR_API_KEY,
)
from app.api.nsmodels.recips import (
    recips_ns,
    recip_model,
    recip_email_model,
    recip_number_model,
    recip_create_parser,
    recip_update_parser,
    recip_email_create_parser,
    recip_email_update_parser,
    recip_number_create_parser,
    recip_number_update_parser,
    recip_response_model,
    recip_list_response_model,
    recip_email_response_model,
    recip_number_response_model,
    message_response_model,
)
from app.api.nsmodels.services import (
    services_ns,
    register_service_parser,
    service_model,
    service_list_response_model,
    service_register_response_model,
    message_response_model as service_message_response_model,
    error_model as service_error_model,
    JWT_OR_API_KEY,
)
